global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8000']

  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9808']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
